const BOT_QUEUE = "BOT_QUEUE";
const BOT_QUEUE_CREATE_POST = "BOT_QUEUE_CREATE_POST";
const BOT_QUEUE_CREATE_POST_DELAY = 2_000;
const BOT_PHOTOS_FOR_POSTS_KEY = "photosForPosts";

// Scenes
const BOT_WIZARD_START = "BOT_WIZARD_START";
const BOT_WIZARD_UPLOAD = "BOT_WIZARD_UPLOAD";

// Actions
const BOT_ACTION_UPLOAD = "upload";
const BOT_ACTION_UPLOAD_SET_DESCRIPTION = "setDescription";

export {
	BOT_QUEUE,
	BOT_QUEUE_CREATE_POST,
	BOT_QUEUE_CREATE_POST_DELAY,
	BOT_PHOTOS_FOR_POSTS_KEY,
	BOT_WIZARD_START,
	BOT_WIZARD_UPLOAD,
	BOT_ACTION_UPLOAD,
	BOT_ACTION_UPLOAD_SET_DESCRIPTION,
};
