const BOT_QUEUE = "BOT_QUEUE";
const BOT_QUEUE_CREATE_POST = "BOT_QUEUE_CREATE_POST";
const BOT_QUEUE_CREATE_POST_DELAY = 3_000;
const BOT_PHOTOS_FOR_POSTS_KEY = "photosForPosts";

export {
	BOT_QUEUE,
	BOT_QUEUE_CREATE_POST,
	BOT_QUEUE_CREATE_POST_DELAY,
	BOT_PHOTOS_FOR_POSTS_KEY,
};
